name: Codecov
on:
  push:

jobs:
  run:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          name: codecov-umbrella
          fail_ci_if_error: true
