on:
  push:

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
    
